version: '3.8'


services:
  backend:
    container_name: guido_backend
    restart: always
    image: guido-backend:1.0
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    ports:
      - "5005:5005"
      - "8000:8000"
    networks:
      - shared-network
    depends_on:
      - redis

  frontend:
    container_name: guido_frontend
    restart: unless-stopped
    image: guido-frontend:1.0
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared-network
  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
